### ISSUE TITLE
[BUG] Non-ideal clock placement

### ISSUE THREAD

**Issue by Hibyehello** [TheWisker/Shikai#11]
### Explanation

When using a long hostname the clock placement is not great. I Just installed it from the AUR. I looked into it but am too unfamiliar with javascript.

As seen here
![image](https://github.com/TheWisker/Shikai/assets/36666883/172191d0-67cf-40d7-b964-d3d0ee256f2e)

### Steps to reproduce

1. Have a long hostname
2. Open the greeter

### Shikai Version

v1.5.1

### Linux Distro

Arch

### LightDM Version

1.32.0

### Greeter Version

3.5.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
Thank you for letting me know, the [latest release](https://github.com/TheWisker/Shikai/releases/tag/v1.5.3) should fix it successfully.
