### ISSUE TITLE
[Enhancement] Way to save states between logins

### ISSUE THREAD

**Issue by car8675309** [TheWisker/Shikai#12]
### Explanation

It can be frustrating to get on the computer and have to switch to my account and preferred window manager every time I go to use the computer after just using it. 

It would be nice to not have to constantly change the login settings every time.  

### Expected Behavior

I would expect that Shikai would remember the user that logged in last and remember the last window manager used by each user. This way login time is fast and simple. 

Another thing that would make logging in fast and simple would be having the cursor automatically be in the password box when lightdm loads up. 

### Additional Context

No additional context, just a note to say that I love the look of Shikai. It is absolutely the most beautiful look I have ever seen for lightdm. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
Those issues will be addressed in the next update, as they, as you said, improve the easiness of the theme. Thanks for the suggestions!

**Comment by TheWisker** [comment]
I am almost done with the next update. I wanted to give an update on this topic as i was not able to get to work the prompt autofocus feature for reasons that seem to be external to the theme. Thus, I opened the following [issue](https://github.com/JezerM/web-greeter/issues/86). Feel free to read it if you want further information as to why I am not able to implement such function at the moment.

**Comment by TheWisker** [comment]
I have *added* in the **latest** release (v1.6.0) a way to add a default user and session.
It is **explained** in the [configuration](https://github.com/TheWisker/Shikai#configuration-) section **under greeter** as the options with keys **default_user** and **default_session**.
I know this is not exactly the same as saving the last user and session, but I believe the majority of the people that use this theme, including me, usually log into the same account and session. Even so, lightdm supports saving the last session used in a .dmrc file in the user's home directory, but web greeter does not seem to pick this up correctly as my theme uses the user.session property that the greeter's API provides and does not preselect the last session.
I will mark this as completed now.
Hope it helps!
