### ISSUE TITLE
[BUG] I can not load the shikai theme with lightdm-webkit2-greeter

### ISSUE THREAD

**Issue by TonyN678** [TheWisker/Shikai#13]
### Explanation

I downloaded the theme from the Arch User Repository, follow the instructions on the github page: changing the theme to "shikai" in the web_greeter.yml file at /etc/lightdm.  After logging out the screen is blank with a textbox asking me whether i want to use the default theme(This is the original theme you got when first use lightdm-webkit2-greeter),

![image](https://github.com/TheWisker/Shikai/assets/131923794/b08af601-ab95-4115-ad73-12de7247873c)

 so i think here lightdm crash maybe because the theme 'shikai' is set in the default file lightdm-webkit2-greeter.conf **and** web-greeter.yml file, i don't set the theme only in the web-greeter.yml is because lightdm would use the theme in the default file lightdm-webkit2-greeter.conf instead of web-greeter.yml file, so i put in both for sure.

I then check to see if the theme 'shikai' is in /usr/share/lightdm-webkit/themes (where all the webkit themes sit) and there is none, but the theme 'shikai' is in /usr/share/web-greeter/themes. I then copy the shikai theme in /sur/share/web-greeter/themes to /usr/share/lightdm-webkit/themes, put shikai as theme name in the lightdm-webkit2-greeter.conf and logout. It still show the same error: a blank screen with a textbox asking for layout/theme change.

At this stage, I honestly don't know what is the issue, I just think maybe the 2 config files has conflict or the theme is not supported by webkit2 greeter.

Thank you for your time and effort reading this post, I am desparate for a solution :)

### Shikai Version

v1.5.1

### Linux Distro

Arch

### LightDM Version

v1.32.0

### Greeter Version

v2.2.5

### Additional Context

I am trying to customise my lightdm looks, that's why I am trying new themes when I come across theme shikai, I notice its installation and setup is different from other webkit-greeter themes that I have tried like glorious or musfealle.

https://github.com/eromatiya/lightdm-webkit2-theme-glorious
https://github.com/pedropenna/musfealle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PowaBanga** [comment]
Personaly it work with web-greeter package from AUR https://aur.archlinux.org/packages/web-greeter

/etc/lightdm/lightdm.conf
`greeter-session=web-greeter`

/etc/lightdm/web-greeter.yml
`    theme=shikay`

**Comment by TonyN678** [comment]
Oh that explains all why the theme shifts with web-greeter. I thought that web-greeter and lightdm-webkit2-greeter are the same thing. Thank you so much, I was considering switching to use the Aether theme.
