### ISSUE TITLE
[Enhancement] Option to remove all animations

### ISSUE THREAD

**Issue by stevenxxiu** [TheWisker/Shikai#16]
### Explanation

I would like an option to remove all animations. Some people like them, some don't.

### Expected Behavior

There's no animations, especially nothing that moves and animates.

### Additional Context

I tried this theme once, coming from the no longer maintained and similar looking [Aether](https://github.com/NoiSek/Aether) theme. The animations really turned me off. If this option is provided, I could try this out again. *Aether* is good, but having something that's still being maintained would be better.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
I will look into adding such option as I think it won't be too hard :)

**Comment by TheWisker** [comment]
I looked into it. The best option to be able to remove all animations is adding the following css code:

* {
    -webkit-transition: none !important;
    -moz-transition: none !important;
    -o-transition: none !important;
    transition: none !important;
}

This gets rid of all animations whilst maintaining all usability.
Unfortunately, as this goal is not aligned with my idea for the project, I will not be adding such a feature myself, as it takes time and effort. You can copy that css code to _general.scss and the run ./scripts/production.sh to make the theme with animations fully disabled or, if you are up for it, make the toggle option yourself and make a pull request. I'm more than happy to merge it if you make it. 

Happy you liked the theme.
