### ISSUE TITLE
Specify default user?

### ISSUE THREAD

**Issue by DillanCMills** [TheWisker/Shikai#18]
Hi, it seems like every time I boot, it defaults to sorting the username list alphabetically. Is there a way to specify a default user, or have it default to the last logged in user?

**Comment by TheWisker** [comment]
I plan to update the project by adding some kind of way to be able to specify the default user as, from what I know, it was something you used to be able to do with Light DM but they remove the feature at some point and as of now the only way is theme-specific.

**Comment by TheWisker** [comment]
I have already made the required changes and will push the new commit push along with the corresponding release of the new version :)

**Comment by TheWisker** [comment]
I have *added* in the **latest** release (v1.6.0) a way to add a default user and session.
It is **explained** in the [configuration](https://github.com/TheWisker/Shikai#configuration-) section **under greeter** as the options with keys **default_user** and **default_session**.
I will mark this as completed now.
Hope it helps!
