### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by cidne** [TheWisker/Shikai#3]
Installed with yay, however, the same error is encountered with a manual install.

Issue:
After entering password I'm confronted with a pop-up error that says:

```
An error ocurred. Do you want to change to default theme?
web-greeter://app//usr/share/web-greeter/themes/shikai/index.js 1: Uncaught TypeError: Cannot read property 'logged_in' of undefined
```

Only options are:
```
Reload theme (doesn't work)
Use default theme (doesn't work)
Cancel (blanks screen)
```

**Comment by teschnei** [comment]
I also encounter this error.  I removed the logged_in notification for now as a workaround.  I believe the same problem happens with wrong_password notification.

**Comment by TheWisker** [comment]
Strangely I did not encounter the error. I am going to look into it now. I will launch a new release with the fix. Thanks for letting me know!

**Comment by TheWisker** [comment]
I fixed the error. It was the most stupid thing it could be! I updated the AUR, so everything should work flawlessly now.
