### ISSUE TITLE
[Enhancement] Adding arabic language!

### ISSUE THREAD

**Issue by Faisal-beep22** [TheWisker/Shikai#5]
Hello, my friend!
 
I love your Lightdm theme and i saw the different langauges and i wanted to add my native language to them.
I have finished translating the the whole page and i think i did a pretty good job!
Just change the txt to a JS file and it will work hopefully!

[arb.txt](https://github.com/TheWisker/Shikai/files/11581684/arb.txt)

**Comment by Faisal-beep22** [comment]
Also i forgot to add the font that i think will go along with the theme of the repo:

https://fonts.google.com/share?selection.family=Noto%20Sans%20Arabic:wght@300

If you need anything else lmk

**Comment by TheWisker** [comment]
Hello, my friend!

I am happy you liked the theme! I will gladly add your language! 
Thanks for translating it!
I will work on it soon.

**Comment by TheWisker** [comment]
You left the field hint: "" without a translation on line 15. I will temporarily use google translate to fill out that field. If you want you can provide me with a more accurate translation.

**Comment by Faisal-beep22** [comment]
I did it on purpose because Arabic is read from right to left not like english from left to right so it requires more tempering with your code so instead i left it empty and used "Hint" translation on every hint notification instead

for demo:

if it was "Hint:", "After 60 seconds of idle the pc will shutdown" will appear as  ( After 60 seconds of idle the pc will shutdown Hint: )

where as if i hard coded it on the translation itself like so:

"","Hint: After 60 seconds of idle the pc will shutdown" it will appear as ( After 60 seconds of idle the pc will shutdown ).

**Comment by Faisal-beep22** [comment]
I did it on purpose because Arabic is read from right to left not like english from left to right so it requires more tempering with your code so instead i left it empty and used "Hint" translation on every hint notification instead

for demo:

if it was "Hint:", "After 60 seconds of idle the pc will shutdown" will appear as ( After 60 seconds of idle the pc will shutdown Hint: )

where as if i hard coded it on the translation itself like so:

"","Hint: After 60 seconds of idle the pc will shutdown" it will appear as ( Hint: After 60 seconds of idle the pc will shutdown ).

**Comment by TheWisker** [comment]
Okey, I just pushed the new version with Arabic language added, I will think of a workaround for that.

**Comment by TheWisker** [comment]
I just realized that it turns itself around! That or I am going nuts. I don't really understand how, but it works.

**Comment by TheWisker** [comment]
I just need your confirmation that everything is correct and I will close this issue. Thanks for everything!

**Comment by Faisal-beep22** [comment]
Mostly needs to delete the "Hint" you need to leave it as I made it so it doesn't cause any headaches.

**Comment by TheWisker** [comment]
Check if it is reversed correctly. I checked and the browser reverses it itself.

**Comment by Faisal-beep22** [comment]
I just checked it is not right

Arabic is from right to left

**Comment by Faisal-beep22** [comment]
Now it is thanks

**Comment by TheWisker** [comment]
Then it is all correct?

**Comment by Faisal-beep22** [comment]
yes just deleted the hint that i added myself so it doesn't look weird

**Comment by Faisal-beep22** [comment]
Thanks for everything dude you are awesome!
